version: '2.1'
services:
  db:
    image: opendronemap/webodm_db
    container_name: db
    expose:
      - "5432"
    volumes:
      - /mnt/user/appdata/opendronemap/dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    oom_score_adj: -100

  webapp:
    image: opendronemap/webodm_webapp
    container_name: webapp
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\""
    volumes:
      - /mnt/user/appdata/opendronemap/appmedia:/webodm/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
      - worker
    environment:
      - WO_PORT=8000
      - WO_HOST
      - WO_DEBUG
      - WO_BROKER=redis://broker:6379/0
      - WO_DEV
      - WO_DEV_WATCH_PLUGINS
    restart: unless-stopped
    oom_score_adj: 0

  broker:
    image: redis
    container_name: broker
    restart: unless-stopped
    oom_score_adj: -500

  worker:
    image: opendronemap/webodm_webapp
    container_name: worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - /mnt/user/appdata/opendronemap/appmedia:/webodm/app/media
    depends_on:
      - db
      - broker
    environment:
      - WO_BROKER=redis://broker:6379/0
      - WO_DEBUG
    restart: unless-stopped
    oom_score_adj: 250
